# Generated by Django 5.2.6 on 2025-10-17 05:27

import django.db.models.deletion
from django.db import migrations, models


def assign_target_memberships(apps, schema_editor):
    DuesReminder = apps.get_model('dues', 'DuesReminder')
    GroupMembership = apps.get_model('groups', 'GroupMembership')

    for reminder in DuesReminder.objects.exclude(group__isnull=True).exclude(target_user__isnull=True):
        if reminder.target_membership_id:
            continue
        membership = GroupMembership.objects.filter(
            group_id=reminder.group_id,
            user_id=reminder.target_user_id,
            status='active',
        ).first()
        if membership:
            reminder.target_membership_id = membership.id
            reminder.save(update_fields=['target_membership'])


class Migration(migrations.Migration):

    dependencies = [
        ('dues', '0003_duesreminder_group'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duesreminder',
            name='target_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dues_reminders', to='groups.groupmembership'),
        ),
        migrations.RunPython(assign_target_memberships, migrations.RunPython.noop),
    ]
