# Generated by Django 5.2.6 on 2025-10-17 05:27

import django.db.models.deletion
from django.db import migrations, models


def assign_memberships(apps, schema_editor):
    Payment = apps.get_model('common', 'Payment')
    Transaction = apps.get_model('common', 'Transaction')
    GroupMembership = apps.get_model('groups', 'GroupMembership')

    for payment in Payment.objects.exclude(group__isnull=True).exclude(user__isnull=True):
        if payment.membership_id:
            continue
        membership = GroupMembership.objects.filter(
            group_id=payment.group_id,
            user_id=payment.user_id,
            status='active',
        ).first()
        if membership:
            payment.membership_id = membership.id
            payment.save(update_fields=['membership'])

    for transaction in Transaction.objects.exclude(group__isnull=True).exclude(user__isnull=True):
        if transaction.membership_id:
            continue
        membership = GroupMembership.objects.filter(
            group_id=transaction.group_id,
            user_id=transaction.user_id,
            status='active',
        ).first()
        if membership:
            transaction.membership_id = membership.id
            transaction.save(update_fields=['membership'])


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_payment_unique_user_year_month_payment_and_more'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='groups.groupmembership'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='groups.groupmembership'),
        ),
        migrations.RunPython(assign_memberships, migrations.RunPython.noop),
    ]
