# Generated by Django 5.2.6 on 2025-10-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbanking', '0002_account_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openbankingaccount',
            options={'ordering': ['alias', 'id']},
        ),
    ]
