# Generated by Django 4.2.25 on 2025-10-30 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('privacy', '개인정보 처리방침'), ('terms', '서비스 약관')], max_length=50, verbose_name='정책 유형')),
                ('version', models.CharField(max_length=50, unique=True, verbose_name='버전')),
                ('content_md', models.TextField(verbose_name='마크다운 본문')),
                ('effective_date', models.DateField(verbose_name='시행일')),
                ('is_active', models.BooleanField(default=False, verbose_name='현재 활성화 여부')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_at', models.DateTimeField(auto_now_add=True, verbose_name='동의 시점')),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.policyversion', verbose_name='동의한 정책 버전')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 동의 이력',
                'unique_together': {('user', 'policy_version')},
            },
        ),
    ]
