# Generated by Django 4.2.25 on 2025-10-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('privacy', '개인정보 처리방침'), ('terms', '서비스 약관'), ('youth', '청소년 보호정책'), ('about', '회사 소개')], max_length=50, unique=True, verbose_name='정책 유형')),
                ('title', models.CharField(max_length=255, verbose_name='정책 제목')),
                ('content_md', models.TextField(verbose_name='마크다운 본문')),
                ('is_active', models.BooleanField(default=False, verbose_name='활성화 여부')),
                ('version', models.CharField(max_length=50, verbose_name='버전')),
                ('effective_date', models.DateField(verbose_name='시행일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
