# Generated by Django 4.2.25 on 2025-10-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyversion',
            name='policy_type',
            field=models.CharField(choices=[('privacy', '개인정보 처리방침'), ('terms', '서비스 약관'), ('youth', '청소년 보호정책'), ('about', '회사 소개')], max_length=50, verbose_name='정책 유형'),
        ),
    ]
