# Generated by Django 4.2.25 on 2025-10-31 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policyversion_policy_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useragreement',
            options={'verbose_name': '사용자 동의 이력', 'verbose_name_plural': '사용자 동의 이력'},
        ),
    ]
