# Generated by Django 4.2.25 on 2025-10-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_alter_useragreement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyversion',
            options={'verbose_name': '정책 버전', 'verbose_name_plural': '정책 버전'},
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='version',
            field=models.CharField(max_length=50, verbose_name='버전'),
        ),
        migrations.AlterUniqueTogether(
            name='policyversion',
            unique_together={('policy_type', 'version')},
        ),
    ]
