# Generated by Django 4.2.25 on 2025-10-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_policyversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyversion',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='정책 제목'),
            preserve_default=False,
        ),
    ]
