# Generated by Django 5.2.6 on 2025-10-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_budget_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['name', 'id']},
        ),
    ]
