name: CI

on:
  push:
    branches: ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort flake8

      - name: Lint
        run: |
          black .
          isort . --profile black
          flake8

      - name: Django checks
        env:
          DJANGO_SECRET_KEY: test-key
          DEBUG: "0"
        run: |
          python manage.py check --deploy
          python manage.py makemigrations --check

      - name: Tests
        env:
          DJANGO_SECRET_KEY: test-key
          DEBUG: "0"
        run: |
          python manage.py test --verbosity=2
